BUS_PREFIX = "BUS-45"
MAX_CAPACITY = 40

DRIVERS_JSON = "drivers.json"

MQTT_BROKER = "localhost"
MQTT_PORT = 1883
MQTT_TOPIC_QUEUE = f"bus/{BUS_PREFIX}/queue"
MQTT_TOPIC_DRIVER = f"bus/{BUS_PREFIX}/driver_event"